apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    sf.devops.project.service: db
  name: db
spec:
  clusterIP: db
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    sf.devops.project.service: db
status:
  loadBalancer: {}
